### ISSUE TITLE
General review of the module

### ISSUE THREAD

**Issue by claudiu-cristea** [pfrenssen/cas_mock_server#3]
Impressive work here! I see this module used by `cas` module itself as right now their functional tests really need a mock endpoint. Great to see the coverage and all Drupal module "rituals" (such as PHPCS) in place. I still have some points while reviewing this as a new module:

[cas_mock_server.info.yml](https://github.com/pfrenssen/cas_mock_server/blob/8.x-1.x/cas_mock_server.info.yml)

- [x] Lacks the `configure` key as we have a settings page.
- [x] Composer requires `"php": ">=7.1.0"`, then let's add the `php` key also here.
- [x] I see we depend on `cas` module. To me looks like the other way around: `cas` should depend on `cas_mock_server` for testing its core functionality, i.e. should add the `test_dependencies` key in its `.info.yml`. But that, I guess, would lead to a circular dependency. Looking into module, I see why we are depending on `cas`. Most important is `CasMockServerConfigOverrider`, and less important is the settings form as tab of the `cas` settings form. IMO, `cas_mock_server` should mock a CAS sever also for other 3rd-party clients that want to do some testing, not only `cas` module. What `CasMockServerConfigOverrider` is doing, is basically doing the job of the test because the test should be in business of setting up the server access URL and info. This helps us a lot but makes the module less generic. What if someone wants to use it for a non-Drupal CAS client? We should allow it, I think. A good compromise would be to conditionally add the `cas` logic in `CasMockServerConfigOverrider`, by testing if the module is installed. Then we support `cas` but not depend on it. The menu issue could be solved by dynamic menu item definition but I would keep it simple, decoupled from the `cas` route.

[composer.json](https://github.com/pfrenssen/cas_mock_server/blob/8.x-1.x/composer.json)

- [x] As we provide Drush commands, don't we depend also on Drush? (need to specify the Drush constraints, e.g. ~9.7). I see it's a suggestion. I would, at least, add it to `require-dev`, so that a developer has its dependencies downloaded, as he could work on Drush command themselves.

[src/Commands/CasMockServerCommands.php](https://github.com/pfrenssen/cas_mock_server/blob/8.x-1.x/src/Commands/CasMockServerCommands.php)

- [x] Let's log some success messages for `CasMockServerCommands::start()` and `::stop()`. E.g. "Started the CAS mock server".
- [x] `CasMockServerCommands::stop()`: shouldn't we explicitly clear any potential users from cache?

[UserManager.php](https://github.com/pfrenssen/cas_mock_server/blob/8.x-1.x/src/UserManager.php)

- [x] I have problem with storing the users in cache. A test, using `cas_mock_server`, might need to perform a general cache clear (such as when enabling a module in test) but still need the CAS users for later step in the same test. But the users are gone. Expirable key-value store, state variable? No strong idea, but I feel we can do this better. We can open a followup to fix this.

[src/Form/LoginForm.php](https://github.com/pfrenssen/cas_mock_server/blob/8.x-1.x/src/Form/LoginForm.php)

- [x] See https://github.com/pfrenssen/cas_mock_server/pull/2

**Comment by pfrenssen** [comment]
> IMO, cas_mock_server should mock a CAS sever also for other 3rd-party clients that want to do some testing, not only cas module.

This is a very good point, there is no reason for us to limit ourselves only to the Drupal CAS module.

> A good compromise would be to conditionally add the cas logic in CasMockServerConfigOverrider, by testing if the module is installed.

I had a look at this but it will not even be necessary to check that the module is enabled, since we already have checks that the CAS module config is being requested. If the module is not enabled this config will never be offered for overriding by the config factory service. I will add a comment to the class explaining this.

**Comment by pfrenssen** [comment]
> Let's log some success messages for CasMockServerCommands::start() and ::stop(). E.g. "Started the CAS mock server".

OK I will add them but at a level that will only make them visible with the `--verbose` option. We should not output anything if the command has succeeded in the normal way.

Ref. [POSIX specification](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap01.html#tag_17_04):

> [...] the diagnostic messages shall be sent to the standard error only when the exit status indicates that an error occurred [...]

I know that a lot of Drush commands violate POSIX and are overly chatty, but this is no reason for me to follow suit. I actually do a lot of shell scripting and outputting unnecessary information makes scripting more difficult.

**Comment by pfrenssen** [comment]
> `CasMockServerCommands::stop()`: shouldn't we explicitly clear any potential users from cache?

Hmmm not sure about this, I added the command to start and stop mainly for being able to turn it off quickly and revert to the standard CAS behaviour while developing. It would be a chore to always have to recreate the users.

But I agree that it would be helpful to have a way to clear the users from the CLI. I will add a `cas-mock-server:reset` command.

**Comment by claudiu-cristea** [comment]
All the remarks were addressed. Thank you!
